# Run Monica with fpm flavor, mariadb, cron, queue, redis, and nginx
#
# You first need to generate the secrets for the encryption key and db password:
# `{ echo -n 'base64:'; openssl rand -base64 32; } | docker secret create app_key -`
# `openssl rand -hex 24 | docker secret create mysql_password -`
#
# You might want to set these variables in you .env file:
#- APP_URL with your domain (https scheme)
#

version: "3.9"

services:
  app: &app
    build: ./app
    image: monica-app
    env_file: .env
    environment:
      - APP_KEY_FILE=/run/secrets/monica-app-key
      - DB_PASSWORD_FILE=/run/secrets/monica-mysql-pass
      - MAIL_USERNAME=/run/secrets/monica-smtp-user
      - MAIL_PASSWORD=/run/secrets/monica-smtp-pass
      - MAIL_FROM_ADDRESS=/run/secrets/monica-smtp-from-user
    volumes:
      - monica-data:/var/www/html/storage
    restart: always
    depends_on:
      - db
      - redis
    secrets:
      - monica-app-key
      - monica-mysql-pass
      - monica-smtp-user
      - monica-smtp-pass
      - monica-smtp-from-user

  db:
    image: mariadb:11
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=monica
      - MYSQL_USER=monica
      - MYSQL_PASSWORD_FILE=/run/secrets/monica-mysql-pass
    volumes:
      - monica-mysqldata:/var/lib/mysql
    restart: always
    secrets:
      - monica-mysql-pass

  redis:
    image: redis:alpine
    restart: always

  cron:
    <<: *app
    command: cron.sh

  queue:
    <<: *app
    command: queue.sh

  web:
    build: ./web
    image: monica-web
    restart: always
    ports:
      - 2580:80
    volumes:
      - monica-data:/var/www/html/storage:ro
    depends_on:
      - app


volumes:
  monica-data:
    external: true
  monica-mysqldata:
    external: true


secrets:
  monica-app-key:
    external: true
  monica-mysql-pass:
    external: true
  monica-smtp-user:
    external: true
  monica-smtp-pass:
    external: true
  monica-smtp-from-user:
    external: true
